In [1]:
# ordinal encoding
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [3]:
df = df[['review', 'education', 'purchased']]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50 non-null     object
 1   education  50 non-null     object
 2   purchased  50 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [8]:
df['review'] = df['review'].astype('category')
df['education'] = df['education'].astype('category')
df['purchased'] = df['purchased'].astype('category')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50 non-null     category
 1   education  50 non-null     category
 2   purchased  50 non-null     category
dtypes: category(3)
memory usage: 670.0 bytes

In [11]:
df['review'].unique()

['Average', 'Poor', 'Good']
Categories (3, object): ['Average', 'Good', 'Poor']

In [12]:
df['education'].unique()

['School', 'UG', 'PG']
Categories (3, object): ['PG', 'School', 'UG']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df[['review', 'education']], df['purchased'], test_size = 0.2, random_state = 42)

In [14]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
oe.fit(X_train)
X_train = oe.transform(X_train)
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [15]:
X_test = oe.transform(X_test)
X_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [17]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
# for target variable, always use labelencoder
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()
le.fit(Y_train)
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [23]:
Y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [24]:
Y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])