In [2]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
#pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

## Fifa Worldcup - 2022 dataset.

You can find the dataset from [here](https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results).

Also you can directly use an url to read the dataset by using `pd.read_csv()` method. Check the below code cell.

In [3]:
# To get the details about the dataset, please visit
# https://www.kaggle.com/datasets/sayanroy729/fifa-worldcup-2022-results

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0

In [4]:
pd.options.display.max_columns = None

In [5]:
df.head(3)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3

### `Q-1:` Use the football dataset. Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

In [6]:
# code here
temp = df.groupby('Team')[['On Target', 'Total Attempts']].sum()
temp['percentage'] = (temp['On Target'] / temp['Total Attempts']) * 100
temp.sort_values('percentage', ascending = False, inplace = True)

In [7]:
temp.reset_index(inplace = True)

In [8]:
temp.head()

         Team  On Target  Total Attempts  percentage
0  Costa Rica          6              11   54.545455
1    Cameroon         14              27   51.851852
2     Ecuador         13              27   48.148148
3   Argentina         48             104   46.153846
4      Brazil         41              90   45.555556

In [9]:
teams = {}
for i in range(temp.shape[0]):
    teams[temp['Team'].values[i]] = temp['percentage'].values[i]
teams

{'Costa Rica': 54.54545454545454,
 'Cameroon': 51.85185185185185,
 'Ecuador': 48.148148148148145,
 'Argentina': 46.15384615384615,
 'Brazil': 45.55555555555556,
 'England': 45.0,
 'Portugal': 40.32258064516129,
 'Ghana': 40.0,
 'Netherlands': 39.02439024390244,
 'Korea Republic': 36.734693877551024,
 'Australia': 36.0,
 'Mexico': 34.883720930232556,
 'France': 34.65346534653465,
 'Germany': 34.32835820895522,
 'Croatia': 33.734939759036145,
 'Spain': 32.69230769230769,
 'Belgium': 32.35294117647059,
 'Serbia': 32.25806451612903,
 'Iran': 31.428571428571427,
 'Uruguay': 31.25,
 'United States': 31.11111111111111,
 'Saudi Arabia': 31.03448275862069,
 'Senegal': 30.76923076923077,
 'Switzerland': 30.555555555555557,
 'Denmark': 30.555555555555557,
 'Japan': 30.23255813953488,
 'Wales': 29.166666666666668,
 'Qatar': 28.57142857142857,
 'Morocco': 28.333333333333332,
 'Tunisia': 26.666666666666668,
 'Poland': 25.0,
 'Canada': 17.647058823529413}

### `Q-2:` Find out how many times the teams are played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [10]:
# code here
df['rank'] = df['Team'].rank(method = 'first')
df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts,rank
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0,95.0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3,39.0
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3,42.0
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0,60.0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,13,1,6,8,5,10,4,6,6,19,74,15,141,95,18,11,1,0,11,3,583,518,22,1,3,15,0,0,79.0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,14,4,8,7,7,20,8,3,2,7,106,15,164,114,23,12,0,0,13,2,491,430,21,3,6,13,0,3,35.0
125,126,63,Morocco,Croatia,F,1,45,1,0,0,7,2,5,5,2,13,1,3,7,16,75,10,150,97,14,8,2,0,11,2,494,428,20,5,3,15,0,0,80.0
126,127,64,Argentina,France,C,3,46,3,0,1,21,9,9,13,8,13,6,8,9,9,163,28,249,172,40,24,4,0,26,4,648,544,20,4,6,22,5,3,7.0
127,128,64,France,Argentina,D,3,40,3,0,1,10,5,3,7,3,15,7,5,4,12,69,9,179,107,14,9,3,0,19,4,516,419,24,3,5,28,4,0,53.0

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [11]:
# code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
 38  rank                             128 non-null    float64
dtypes: float64(1), int64(35), object(3)
memory usage: 39.1+ KB

In [12]:
df.describe()

,Sl. No,Match No.,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts,rank
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,32.500000,1.343750,43.476562,1.203125,0.117188,0.914062,11.257812,4.007812,4.835938,6.914062,4.343750,13.562500,4.671875,4.906250,4.648438,12.234375,92.703125,12.453125,169.281250,109.476562,14.812500,8.265625,1.726562,0.023438,12.320312,1.976562,502.859375,430.929688,19.523438,4.898438,4.468750,14.250000,0.335938,1.429688,64.500000
std,37.094474,18.545539,1.342448,11.442403,1.324270,0.322907,1.150333,5.406683,2.588576,2.610630,3.998085,2.733397,6.901729,2.886595,3.080131,2.936573,6.176517,29.440547,18.152399,34.120661,30.776298,7.230458,5.101311,1.514834,0.151883,4.691983,1.731891,160.160487,160.893724,8.596799,3.520111,2.774852,4.712189,0.941412,1.389973,37.094474
min,1.000000,1.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,32.000000,0.000000,56.000000,19.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,225.000000,156.000000,4.000000,0.000000,0.000000,5.000000,0.000000,0.000000,1.000000
25%,32.750000,16.750000,0.000000,35.000000,0.000000,0.000000,0.000000,7.750000,2.000000,3.000000,4.000000,3.000000,8.000000,2.000000,3.000000,3.000000,8.000000,72.750000,7.000000,149.500000,87.750000,10.000000,5.000000,1.000000,0.000000,9.000000,1.000000,398.250000,323.250000,13.000000,3.000000,2.000000,11.000000,0.000000,0.000000,32.750000
50%,64.500000,32.500000,1.000000,45.000000,1.000000,0.000000,1.000000,10.000000,4.000000,4.000000,6.000000,4.000000,12.000000,4.500000,4.000000,4.000000,11.000000,93.000000,9.000000,170.500000,106.000000,15.000000,8.000000,2.000000,0.000000,12.000000,2.000000,495.500000,419.000000,19.000000,4.000000,4.000000,14.000000,0.000000,1.000000,64.500000
75%,96.250000,48.250000,2.000000,51.000000,2.000000,0.000000,1.000000,14.000000,6.000000,6.000000,9.000000,5.000000,18.000000,7.000000,6.250000,6.000000,16.250000,111.250000,14.000000,188.000000,129.000000,20.000000,11.000000,2.000000,0.000000,15.000000,3.000000,589.500000,519.750000,24.000000,6.000000,6.000000,17.000000,0.000000,3.000000,96.250000
max,128.000000,64.000000,7.000000,78.000000,7.000000,1.000000,6.000000,32.000000,13.000000,17.000000,24.000000,15.000000,36.000000,13.000000,16.000000,19.000000,29.000000,186.000000,192.000000,259.000000,192.000000,40.000000,27.000000,8.000000,1.000000,30.000000,10.000000,1070.000000,994.000000,53.000000,25.000000,14.000000,30.000000,5.000000,3.000000,128.000000

In [13]:
df.isnull().sum()

Sl. No                             0
Match No.                          0
Team                               0
Against                            0
Group                              0
Goal                               0
Possession (%)                     0
Inside Penalty Area                0
Outside Penalty Area               0
Assists                            0
Total Attempts                     0
On Target                          0
Off Target                         0
Target in Penalty                  0
Target from Outside                0
Left Channel                       0
Left Inside Channel                0
Central Channel                    0
Right Inside Channel               0
Right Channel                      0
Receptions MD                      0
Receptions D                       0
Attempted Line Breaks              0
Completed Line Breaks              0
Attempted Defensive Line Breaks    0
Completed Defensive Line Breaks    0
Yellow Cards                       0
Red Cards                          0
Fouls Against                      0
Offsides                           0
Passes                             0
Passes Completed                   0
Crosses                            0
Crosses Completed                  0
Corners                            0
Free Kicks                         0
Penalties Scored                   0
Pts                                0
rank                               0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [15]:
df.drop(columns = ['Sl. No', 'Match No.', 'Red Cards', 'Pts'], inplace = True)

In [16]:
df.head()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,rank
0,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,15,3,453,387,10,5,1,19,0,95.0
1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,15,4,484,419,26,10,3,17,1,39.0
2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,9,2,810,733,29,9,8,16,0,42.0
3,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,14,2,232,156,11,3,0,10,1,60.0
4,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,13,2,391,326,22,8,6,14,0,101.0

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [17]:
df['rank'] = df['rank'].astype(np.int16)

In [18]:
df['rank']

0       95
1       39
2       42
3       60
4      101
      ...
123     79
124     35
125     80
126      7
127     53
Name: rank, Length: 128, dtype: int16

In [19]:
# code here
df.set_index('rank', inplace = True)

In [20]:
df.sort_index()

,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored
rank,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Argentina,Saudi Arabia,C,1,51,1,0,0,14,6,6,10,4,12,4,5,8,18,91,27,195,127,10,8,0,7,10,593,525,36,15,9,21,1
2,Argentina,Mexico,C,2,50,1,1,2,5,2,3,2,3,10,6,2,4,12,89,2,150,100,10,5,1,15,2,533,464,14,2,4,23,0
3,Argentina,Poland,C,2,67,1,1,2,25,13,8,10,15,25,8,7,10,26,150,36,141,126,20,16,1,11,0,862,814,22,5,9,5,0
4,Argentina,Australia,C,2,53,2,0,1,14,5,7,11,3,15,6,11,2,17,127,8,181,135,16,8,0,8,4,711,635,6,1,1,15,0
5,Argentina,Netherlands,C,2,44,2,0,1,15,6,8,5,10,7,7,13,6,17,104,7,203,122,24,8,8,18,2,603,511,16,4,8,30,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Uruguay,Portugal,H,0,35,0,0,0,10,3,6,6,4,13,8,4,5,9,94,6,150,86,17,11,2,16,0,390,306,18,5,2,13,0
125,Uruguay,Ghana,H,2,39,2,0,1,12,7,5,7,5,7,2,13,3,17,186,14,186,124,24,14,3,11,2,446,361,15,4,2,20,0
126,Wales,United States,B,1,39,1,0,0,7,3,3,5,2,7,2,5,2,7,73,9,174,103,17,8,2,10,1,409,321,15,6,3,15,1
127,Wales,Iran,B,0,51,0,0,0,10,3,4,5,5,18,3,8,11,13,101,13,208,129,17,8,1,9,2,508,413,20,5,2,12,0
128,Wales,England,B,0,33,0,0,0,7,1,3,1,6,7,1,2,0,4,46,1,104,55,4,1,2,16,1,325,261,4,1,1,10,0

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [21]:
# code here
df1 = pd.read_csv(' https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv')
df1.head()

HTTPError: HTTP Error 400: Bad Request

In [ ]:
df1.dropna(subset= 'Age', inplace = True)
df1.head()

In [ ]:
df2 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv')
df2.head(2)

In [ ]:
df2['Age'] = df2['Age'].fillna(20)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [22]:
# code here
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv')
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [25]:
changed_name = {'Delhi Daredevils':'Delhi Capitals', 
                'Kings XI Punjab':'Punjab Kings',
                'Rising Pune Supergiants':'Rising Pune Supergiant'}
df.replace(changed_name.keys(), changed_name.values(), inplace = True)
df[df['Team1'] == 'Delhi Daredevils']

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

In [ ]:
df['Team1'] = df['Team1'].str.replace('Delhi Daredevils', 'Delhi Capitals')
df['Team2'] = df['Team2'].str.replace('Delhi Daredevils', 'Delhi Capitals')
df['WinningTeam'] = df['WinningTeam'].str.replace('Delhi Daredevils', 'Delhi Capitals')
df['Team1'].value_counts()

In [ ]:
df['Team1'] = df['Team1'].str.replace('Kings XI Punjab', 'Punjab Kings')
df['Team2'] = df['Team2'].str.replace('Kings XI Punjab', 'Punjab Kings')
df['WinningTeam'] = df['WinningTeam'].str.replace('Kings XI Punjab', 'Punjab Kings')

df['Team1'] = df['Team1'].str.replace('Rising Pune Supergiants', 'Rising Pune Supergiant')
df['Team2'] = df['Team2'].str.replace('Rising Pune Supergiants', 'Rising Pune Supergiant')
df['WinningTeam'] = df['WinningTeam'].str.replace('Rising Pune Supergiants', 'Rising Pune Supergiant')
df['Team1'].value_counts()

In [ ]:
df1 = df.dropna(subset = ['WinningTeam'])
df1.head()

In [ ]:
ipl = pd.DataFrame()
ipl['Total_matches'] = df1['Team1'].value_counts() + df['Team2'].value_counts()
ipl

In [ ]:
ipl['wins'] = df1.groupby(['WinningTeam'])['ID'].count()
ipl

In [ ]:
ipl['home_matches'] = df1['Team1'].value_counts()
ipl

In [ ]:
ipl['home_wins'] = df[df['Team1'] == df['WinningTeam']]['Team1'].value_counts()
ipl

In [ ]:
ipl['away_matches'] = ipl['Total_matches'] - ipl['home_matches']
ipl['away_wins'] = ipl['wins'] - ipl['home_wins']
ipl

In [ ]:
ipl['win%'] = (ipl['wins'] / ipl['Total_matches']) * 100
ipl['home_wins%'] = (ipl['home_wins'] / ipl['home_matches']) * 100
ipl['away_wins%'] = (ipl['away_wins'] / ipl['away_matches']) * 100
ipl

In [ ]:
ipl.sort_values(by = 'win%', ascending = False)

###`Q-7:` Venues with most "no result" matches.

In [ ]:
# code here
df[df['WinningTeam'].isna()]['Venue'].value_counts().sort_values(ascending = False).head(1)

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
temp = df[df['MatchNumber'] == 'Final']
temp

In [ ]:
# code here
players = pd.concat([temp['Team1Players'] ,temp['Team2Players']])
players

In [ ]:
players.str.split(',').explode().str.strip('[').str.strip(']').value_counts().idxmax()

In [ ]:
players_dict = {}
for i in range(temp['Players'].shape[0]):
    for player in temp['Players'].values[i]:
        if player in players_dict:
            players_dict[player] += 1
        else:
            players_dict[player] = 1
most = dict(sorted(players_dict.items(), key = lambda x: x[1], reverse = True))
most

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here
temp = df[(df['Season'] == '2015')]
temp.head(2)

In [ ]:
points_table = pd.DataFrame()
points_table['No_of_matches'] = temp['Team1'].value_counts() + temp['Team2'].value_counts()
points_table

In [ ]:
points_table['wins'] = temp['WinningTeam'].value_counts()
points_table

In [ ]:
s1 = temp[temp['WinningTeam'].isna()]['Team1'].value_counts()

In [ ]:
s2 = temp[temp['WinningTeam'].isna()]['Team2'].value_counts()

In [ ]:
points_table['No result'] = pd.concat([s1, s2]).groupby(level = 0).sum()
points_table['No result'] = points_table['No result'].fillna(0)

In [ ]:
points_table

In [ ]:
points_table['points'] = (points_table['wins'] * 2) + (points_table['No result'] * 1)
points_table

In [ ]:
points_table = points_table.sort_values(by = 'points', ascending  = False)

In [ ]:
def point_table(season):
    temp = (df[df['Season'] == season])
    points_table = pd.DataFrame()
    points_table['MatchesPlayed'] = temp['Team1'].value_counts() + temp['Team2'].value_counts()
    points_table['MatchesWon'] = temp['WinningTeam'].value_counts()
    points_table['NoResult'] = pd.concat([temp[temp['WinningTeam'].isna()]['Team1'].value_counts(), temp[temp['WinningTeam'].isna()]['Team2'].value_counts()]).groupby(level = 0).sum()
    points_table['NoResult'] = points_table['NoResult'].fillna(0)
    points_table['Points'] = (points_table['MatchesWon'] * 2) + (points_table['NoResult'] * 1)
    points_table = points_table.sort_values(by = 'Points', ascending  = False)
    return points_table
point_table('2022')

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here
points_table